### ISSUE TITLE
Explota al introducir valores muy largos .

### ISSUE THREAD

**Issue by Randy-Fabian-Belliard** [david-o-rosario1201/Parcial1_Ap1_DavidRosario#1]
https://github.com/david-o-rosario1201/Parcial1_Ap1_DavidRosario/blob/149198256564ad92629b30bd2497480a55b4e110/Models/Metas.cs#L17

**Comment by david-o-rosario1201** [comment]
Ya Arreglé que el monto mínimo sea 0.01 y el máximo sea 10,000,000,000

**Comment by david-o-rosario1201** [comment]
Ya Arreglé que el monto mínimo sea 0.01 y el máximo sea 10,000,000,000
