### ISSUE TITLE
No tiene una forma de poder filtrar en la consulta.

### ISSUE THREAD

**Issue by Randy-Fabian-Belliard** [david-o-rosario1201/Parcial1_Ap1_DavidRosario#2]
https://github.com/david-o-rosario1201/Parcial1_Ap1_DavidRosario/blob/149198256564ad92629b30bd2497480a55b4e110/Components/Pages/MetasPages/Index.razor#L7

**Comment by david-o-rosario1201** [comment]
Agregué el filtro en el index.
