### ISSUE TITLE
No está validando que no existan la misma descripción de meta.

### ISSUE THREAD

**Issue by Randy-Fabian-Belliard** [david-o-rosario1201/Parcial1_Ap1_DavidRosario#3]
https://github.com/david-o-rosario1201/Parcial1_Ap1_DavidRosario/blob/149198256564ad92629b30bd2497480a55b4e110/Services/MetasService.cs#L17

**Comment by david-o-rosario1201** [comment]
Ahora mi proyecto valida que no exista la misma descripción.
